### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by zhao123ying** [liuweide01/GQNet-Few-shot-segmentation#1]
Hi Author, I recently read your article "Few-Shot Segmentation with Global and Local Contrastive Learning" and am very interested in your work, but have some questions.
Could you provide the weights of resnet_unsuper ('. /checkpoint_2000.pth.tar') and the training file of Prior extractor.
Looking forward to your reply, thanks a lot!

**Comment by liuweide01** [comment]
You can download from 
https://entuedu-my.sharepoint.com/:u:/g/personal/weide001_e_ntu_edu_sg/EfbErzwMhUtDhBdcxboUjaIB8C-sibMKLjm5lx4rkNwt7A?e=eHhG4J
